# Generated by Django 5.1.1 on 2024-09-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comodos', to='imoveis.imovel')),
            ],
        ),
    ]
